pipeline {
  agent {
    kubernetes {
      yaml """
kind: Pod
metadata:
  name: aurbuild
spec:
  containers:
  - name: aurbuild
    workingDir: /tmp/jenkins
    image: brokenpip3/dockerbaseciarch:2.3
    imagePullPolicy: Always
    envFrom:
      secretRef:
        name: jenkins-aur-repo
    command:
      - "sh"
      - "-c"
      - 'touch /tmp/build.log && tail -f /tmp/build.log'
    tty: true
    resources:
      limits:
        memory: 2Gi
        cpu: 1500m
        ephemeral-storage: 10Gi
      requests:
        memory: 1Gi
        cpu: 500m
        ephemeral-storage: 10Gi
    volumeMounts:
      - name: repo-pvc
        mountPath: /srv/repo
  volumes:
  - name: repo-pvc
    persistentVolumeClaim:
      claimName: jenkins-aur-packages
"""
    }}
  options { disableConcurrentBuilds()
            timeout(time: 15, unit: 'MINUTES')
          }
  parameters {
        string(name: 'PACKAGENAME', defaultValue: 'trizen', description: 'Aur package to build')}

  stages {
    stage("Setname") {
            steps {
                // use name of the patchset as the build name
                buildName "aur-job-${params.PACKAGENAME} #${BUILD_NUMBER}"
                buildDescription "${BUILD_NUMBER}"
            }
        }
    stage('pacman update') {
      steps {
		    container('aurbuild') {
            sh 'sudo pacman -Sy'
        }
       }
      }
    stage('gpg keys') {
      steps {
		    container('aurbuild') {
            sh './build-package/gpgkeys.sh'
        }
       }
      }
    stage("download") {
      steps {
		    container('aurbuild') {
            sh "curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/${params.PACKAGENAME}.tar.gz"
            sh "tar -xvf ${params.PACKAGENAME}.tar.gz | tee -a /tmp/build.log"
        }
      }
    }
    stage('install dep') {
      steps {
		container('aurbuild')
    {
      sh "cd ${params.PACKAGENAME} && makepkg -s -o --noconfirm"
    }
    }
    }
    stage('build') {
      steps {
		container('aurbuild')
    {
      sh "cd ${params.PACKAGENAME} && makepkg -scf --noconfirm"
    }
    }
    }
    stage('update repo') {
      steps {
	    container('aurbuild')
          {
          sh "repo-add -R -p /srv/repo/needrelax.db.tar.zst /srv/repo/${params.PACKAGENAME}-*"
          }
    }
    }
}
// Since we are using emptydir avoid to fill the underlying compute node fs
post {
         always {
            cleanWs()
              }
    }

}
